spring:
  application:
    name: auth-service
#  jpa:
#    hibernate.ddl-auto: update
#    show-sql: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

security:
  jwt:
    signing-key: should-be-externally-configured

server:
  port: 8082
